### ISSUE TITLE
[ESP8266] error: 'lfs_mlist_isopen' defined but not used [-Werror=unused-function]

### ISSUE THREAD

**Issue by nliviu** [mongoose-os-libs/vfs-fs-lfs#3]
Building the empty application for esp8266 with mos latest issues the error in the title
```
vfs-fs-lfs/littlefs/lfs.c:450:13: error: 'lfs_mlist_isopen' defined but not used [-Werror=unused-function]
```

Adding `--cflags-extra '-Wno-unused-function'` to the build command silences it.

**Comment by rojer** [comment]
fixed, thank you!
